### ISSUE TITLE
Consider making a UBI variable other than adult the slack variable

### ISSUE THREAD

**Issue by MaxGhenis** [UBICenter/uk#19]
Low-priority thought: Since we're going to round UBI amounts to the nearest 5-pound increment, we might be able to shrink the budget error by rounding a UBI amount that affects fewer people than the adult one. For example, rounding the true-optimal adult UBI from 98 to 100 would produce a bigger deficit than doing the same for the child or pensioner UBI.

**Comment by nikhilwoodruff** [comment]
In the most recent analysis [notebook](https://colab.research.google.com/drive/1yyahzpnxQYAidkVIiNkWxejO7OcZkPkA?usp=sharing), I'm getting rounding errors in the UBI amounts putting the net cost of the reforms at about £15bn each.

**Comment by MaxGhenis** [comment]
Closing as we've moved from integer-based grid search to differential evolution, where the slack variable shouldn't matter for the end result.
