### ISSUE TITLE
Create person-reform dataset

### ISSUE THREAD

**Issue by MaxGhenis** [UBICenter/uk#24]
How about this schema, with one row per person per reform, i.e. 3x # person records:

* Person-level demographics:
  - Disability status
  - Region
  - Age group
  - Weight (household weight)
* Baseline household-level:
  - Net income
  - Net income decile
  - Capital income
  - Family archetype
  - Housing benefit receipt (needs to be aggregated to household from BU)
* Household-level reform effects:
  - Net income
  - Change in net income
  - % change in net income
  - UBI amount
  - Change in tax liability
  - Change in benefits

**Comment by nikhilwoodruff** [comment]
Yeah I think this works and is probably a bit simpler
